### ISSUE TITLE
Do you know how to compile LLVM IR into risv32imf?

### ISSUE THREAD

**Issue by hughperkins** [sifive/riscv-llvm#12]
Hi,

I have an LLVM IR file that includes code like:

```
  %18 = load float, float* %17, align 4
  %19 = load float, float* %7, align 4
  %20 = fadd contract float %19, %18
```
You can see that at this point there is a call to `fadd`.

Then I use llc, from llvm 14, to attempt to convert to riscv32imf:

```
llc --march riscv32 sum_floats-device.ll -o sum_floats-device.s
```

The output however is for risvc32i, without float extensions, because the `fadd` gets converted to:
```
	lw	a1, 0(a0)
	lw	a0, -28(s0)
	call	__addsf3@plt
```
i.e. a software  shim for `fadd`, rather than a hardwre `fadd`.

I've poked around at this for several hours, trying different things, e.g.
```
clang --target=riscv32 -march=rv32imf \
     -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include \
    examples/cpp_single_source/sum_floats/build_bash/sum_floats-device.ll -S
```
... which gives no error message, but still converts the `fadd` into a function call to `__sf3@plt`

or ...
```
clang --target=riscv32 -march=rv32gc \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include \
    examples/cpp_single_source/sum_floats/build_bash/sum_floats-device.ll -S
```

... which at least gives a different error message
```
Hard-float 'd' ABI can't be used for a target that doesn't support the D instruction set extension (ignoring target-abi)
```

Thoughts on how I can convert an LLVM IR file, contining `fadd` into a risvc32imf file, that continues to contain calls to `fadd`?

**Comment by zakk0610** [comment]
https://godbolt.org/z/6qGsTPbGn
You need to use `-mattr` to enable floating extension, and `-mattr=help` would list available options.

**Comment by hughperkins** [comment]
Fantastic! That works :)

By the way, just on the off-chance (and I have a solution already if this is not possible), does there happen to be an option to use the Zfinx extension, https://github.com/riscv/riscv-zfinx/blob/main/zfinx-1.0.0-rc.pdf ? (Not a biggie if not; unlike the float and multiplication, which would have caused me huge amounts of pain if there wasnt a way to handle those :) )

**Comment by hughperkins** [comment]
(Well... I have a workaround, but I just realized it relies on any program being built not having more than 31 int and float registers combined...)

**Comment by hughperkins** [comment]
Oh, might be in llvm 14 :)
